aiven/aiven-repositories-for-opensearch

src/integration-test/java/io/aiven/elasticsearch/repositories/gcs/GcsRepositoryPluginIT.java, src/main/java/io/aiven/elasticsearch/repositories/gcs/GcsBlobStore.java, src/main/java/io/aiven/elasticsearch/repositories/gcs/GcsRepositoryPlugin.java, src/main/java/io/aiven/elasticsearch/repositories/gcs/GcsSettingsProvider.java, src/test/java/io/aiven/elasticsearch/repositories/DummySecureSettings.java
1. lazy load initialization removed
2. improve IT test, now repository creates for cluster
=> improvements

repository-commons/src/main/java/io/aiven/elasticsearch/repositories/AbstractRepositoryPlugin.java, repository-commons/src/main/java/io/aiven/elasticsearch/repositories/BlobStoreRepository.java, repository-commons/src/main/java/io/aiven/elasticsearch/repositories/CommonSettings.java, repository-commons/src/main/java/io/aiven/elasticsearch/repositories/RepositoryBlobContainer.java, repository-commons/src/main/java/io/aiven/elasticsearch/repositories/RepositorySettingsProvider.java, repository-commons/src/main/java/io/aiven/elasticsearch/repositories/RepositoryStorageIOProvider.java, repository-commons/src/test/java/io/aiven/elasticsearch/repositories/RepositoryBlobContainerTest.java
Add common abstraction for plugins, which helps to develop new one faster
=> Add common abstraction for plugins

repository-commons/src/main/java/io/aiven/elasticsearch/repositories/AbstractRepositoryPlugin.java, repository-commons/src/main/java/io/aiven/elasticsearch/repositories/BlobStoreRepository.java, repository-commons/src/main/java/io/aiven/elasticsearch/repositories/CommonSettings.java, repository-commons/src/main/java/io/aiven/elasticsearch/repositories/RepositorySettingsProvider.java, repository-commons/src/main/java/io/aiven/elasticsearch/repositories/RepositoryStorageIOProvider.java, repository-commons/src/main/java/io/aiven/elasticsearch/repositories/io/CryptoIOProvider.java, repository-commons/src/test/java/io/aiven/elasticsearch/repositories/io/CryptoIOProviderTest.java, repository-gcs/src/main/java/io.aiven.elasticsearch.repositories.gcs/GcsRepositoryStorageIOProvider.java, repository-gcs/src/main/java/io.aiven.elasticsearch.repositories.gcs/GcsSettingsProvider.java, repository-gcs/src/test/java/io.aiven.elasticsearch.repositories.gcs/GcsSettingsProviderTest.java
Add common method for loading/saving encryption key
=> Add common method for loading/saving encryption key

repository-commons/src/main/java/io/aiven/elasticsearch/repositories/CommonSettings.java
Set maximum chunk size to 64GB
=> Set maximum chunk size to 64GB

repository-commons/src/main/java/io/aiven/elasticsearch/repositories/CommonSettings.java, repository-commons/src/main/java/io/aiven/elasticsearch/repositories/RepositoryStorageIOProvider.java, repository-commons/src/main/java/io/aiven/elasticsearch/repositories/io/CryptoIOProvider.java, repository-gcs/src/main/java/io.aiven.elasticsearch.repositories.gcs/GcsRepositoryStorageIOProvider.java, repository-gcs/src/main/java/io.aiven.elasticsearch.repositories.gcs/GcsSettingsProvider.java, repository-gcs/src/main/java/io.aiven.elasticsearch.repositories.gcs/GcsStorageSettings.java, repository-gcs/src/test/java/io.aiven.elasticsearch.repositories.gcs/GcsSettingsProviderTest.java
1. Exclude `BUCKET_NAME` variable from common repo settings
2. Wrap up all calls to GCS with `StorageException`
3. Remove redundant `reapositoryType` variable from `RepositoryStorageIOProvier` class
=> Miscs refactring

build.gradle
=> Bump up ES to version 7.9.3

repository-commons/src/main/java/io/aiven/elasticsearch/repositories/RepositoryStorageIOProvider.java
When plugin read enc key from metadata InputStream remained open, which is a memory leak.
=> Fix problem with open InputStream

repository-commons/build.gradle
bump up zstd lib version to 1.4.5-12
=> bump up zstd lib veriosn

repository-commons/src/main/java/io/aiven/elasticsearch/repositories/AbstractRepositoryPlugin.java, repository-commons/src/main/java/io/aiven/elasticsearch/repositories/security/Decryption.java, repository-commons/src/main/java/io/aiven/elasticsearch/repositories/security/Encryption.java, repository-commons/src/main/java/io/aiven/elasticsearch/repositories/security/EncryptionKeyProvider.java, repository-commons/src/test/java/io/aiven/elasticsearch/repositories/RsaKeyAwareTest.java
Due to the JceSecurity memory leak, we need to use boucy castle provider
differently.
=> Fix memory leak

repository-commons/src/main/java/io/aiven/elasticsearch/repositories/AbstractRepositoryPlugin.java, repository-gcs/src/main/resources/plugin-security.policy, repository-s3/src/main/resources/plugin-security.policy
Additional permission insertProvider.BC has been added in GCS and S3 plugin
=> Add additional permissions for BC

repository-azure/build.gradle, repository-azure/src/integration-test/java/io/aiven/elasticsearch/repositories/azure/AzureRepositoryPluginIT.java, repository-azure/src/main/java/io/aiven/elasticsearch/repositories/azure/AzureClient.java, repository-azure/src/main/java/io/aiven/elasticsearch/repositories/azure/AzureRepositoryPlugin.java, repository-azure/src/main/java/io/aiven/elasticsearch/repositories/azure/AzureRepositoryStorageIOProvider.java, repository-azure/src/main/java/io/aiven/elasticsearch/repositories/azure/AzureSettingsProvider.java, repository-azure/src/main/java/io/aiven/elasticsearch/repositories/azure/AzureStorageSettings.java, repository-azure/src/main/java/io/aiven/elasticsearch/repositories/azure/FilesListContainer.java, repository-azure/src/main/resources/plugin-descriptor.properties, repository-azure/src/main/resources/plugin-security.policy, repository-azure/src/test/java/io/aiven/elasticsearch/repositories/azure/AzureClientTest.java, repository-azure/src/test/java/io/aiven/elasticsearch/repositories/azure/AzureSettingsProviderTest.java, repository-azure/src/test/java/io/aiven/elasticsearch/repositories/azure/AzureStorageSettingsTest.java, settings.gradle
ES Miscrosoft Repository plug-in implementation
=> Azure repository

repository-gcs/build.gradle, repository-gcs/src/integration-test/java/io/aiven/elasticsearch/repositories/gcs/GcsRepositoryPluginIT.java
1. Refactoring of GCS integration test
2. Bump up GSC client to 1.113.1
=> Gcs it test refactoring

.github/workflows/codeql-analysis.yml, .github/workflows/create_release.yml, .github/workflows/master_push_workflow.yml, .github/workflows/pull_request_workflow.yml, .github/workflows/release_pr_workflow.yml
=> add Github wrkflows

repository-gcs/src/main/java/io.aiven.elasticsearch.repositories.gcs/GcsSettingsProvider.java, repository-gcs/src/test/java/io.aiven.elasticsearch.repositories.gcs/GcsSettingsProviderTest.java
Proxy Username and password are optional
=> Proxy Username and password are optional

.github/workflows/create_release.yml, .github/workflows/create_release_azure.yml, .github/workflows/create_release_gcs.yml, .github/workflows/create_release_s3.yml
Fix paths in create release workflows
=> Fix paths in create release wrkflows

repository-s3/src/main/java/io/aiven/elasticsearch/repositories/s3/S3RepositoryStorageIOProvider.java
The S3StorageIO::listFiles method, returned wrong file name
=> S3StorageIO::listFiles fixed

build.gradle
Use official Opensearch release artifacts (instead of snapshots). 
See please [1].
[1] https://discuss.opendistrocommunity.dev/t/maven-repository-artifacts-for-plugin-development/6406/7%5D
=> Use official Opensearch release artifacts

repository-commons/src/main/java/io/aiven/elasticsearch/repositories/RepositoryBlobContainer.java
Replace logger info to debug level
=> Replace info logging to debug

repository-azure/src/main/java/io/aiven/elasticsearch/repositories/azure/AzureRepositoryStorageIOProvider.java
Used the wrong client to work with BlobContainer
=> Used the wrong client to work with BlobContainer

repository-s3/src/main/java/io/aiven/elasticsearch/repositories/s3/S3ClientProvider.java, repository-s3/src/main/java/io/aiven/elasticsearch/repositories/s3/S3RepeatableInputStream.java, repository-s3/src/main/java/io/aiven/elasticsearch/repositories/s3/S3RepositoryPlugin.java, repository-s3/src/main/java/io/aiven/elasticsearch/repositories/s3/S3RepositoryStorageIOProvider.java, repository-s3/src/main/java/io/aiven/elasticsearch/repositories/s3/S3SettingsProvider.java, repository-s3/src/test/java/io/aiven/elasticsearch/repositories/s3/S3RepeatableInputStreamTest.java, repository-s3/src/test/java/io/aiven/elasticsearch/repositories/s3/S3StorageIOTest.java
Added S3RepeatableInputStream to read snapshot data properly in case of IO failures
=> S3 repeatable stream

build.gradle
- Bump up Opensearch version to 1.2.0
- Bump up Jackson version to 2.12.5
=> Bump up versions

build.gradle
Bump up Opensearch version to 1.3.0
=> Bump up Opensearch version to 1.3.0

repository-commons/src/main/java/io/aiven/elasticsearch/repositories/io/CryptoIOProvider.java
- Use ZstdInputStreamNoFinalizer and ZstdOutputStreamNoFinalizer
- Use RecyclingBufferPool for ZST input and iutput streams
- Use BufferedOutputStream and BufferedInputStream to reduce native
calls
=> Zstd optimization

build.gradle
=> Bump up OpenSearch to 1.3.1
